# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table entry (
  id                            bigint generated by default as identity not null,
  name                          varchar(255) not null,
  title                         varchar(255) not null,
  message                       varchar(255) not null,
  create_date                   timestamp,
  constraint pk_entry primary key (id)
);

create table user (
  user_id                       bigint generated by default as identity not null,
  name                          varchar(255),
  email                         varchar(255),
  password                      varchar(255),
  constraint pk_user primary key (user_id)
);


# --- !Downs

drop table if exists entry;

drop table if exists user;

